apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: predict
  name: predict
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predict
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: predict
    spec:
      containers:
      - name: predict
        image: nvcr.io/nvidia/pytorch:20.11-py3
        ports:
          - containerPort: 5000
            name: flask-port
        command:
        - bash
        - -c
        - |
          git clone https://github.com/THULiusj/gke-pytorch-inference.git
          cd gke-pytorch-inference
          pip install flask==1.1.2
          FLASK_ENV=development FLASK_APP=app.py flask run --host=0.0.0.0
        resources:
          limits:
            nvidia.com/gpu: 1
status: {}
